### ISSUE TITLE
Server version don't work

### ISSUE THREAD

**Issue by SirEdvin** [Funwayguy/NPC_Integration#1]
You use directly 

``` java
QuestController.instance.quests
```

But this code can be used only on server side. Please, use server-client logic. For example, you can see my version.

**Comment by Funwayguy** [comment]
I've taken a look at your version and although yes there may be an issue with client-server accessing of NPC quests, you are also tweaking a lot of things elsewhere that should not be changed especially with the build scripts. The solution you've provided could also breakdown in some cases (progress update while UI is open) so I will be providing my own fix for that later or I'll talk to Noppes about an ideal way to access his quest database.

**Comment by SirEdvin** [comment]
Thank you for answering :)
Sorry about buildscript changes, I try fix it in few days.
Good luck with fix.

**Comment by Funwayguy** [comment]
I've posted a new build which should fix this issue and allow for some localisations that were previously missing.
