### ISSUE TITLE
NoClassDefFoundError on Dedicated Server

### ISSUE THREAD

**Issue by kreezxil** [Funwayguy/NPC_Integration#14]
Issue:  3.4.2.4 crashes dedicated server Forge 1.12.2 build 2705

Notes:
     on startup, NoClassDefFoundError. All dependencies are installed. I suspect it's looking for a client side class.

crash report:
https://gist.github.com/c39d8e6f16157524ed4273c315931a47

fml server latest:
https://gist.github.com/5e828d5de10a9d7af6888f501a70efac

**Comment by kreezxil** [comment]
I removed NPC Integration from my server and the server booted fine without issue. So it certainly appears to be looking for something client side in the IPacketHandler.

**Comment by Funwayguy** [comment]
Missed the email notice last time but I got this one. Kinda weird how NPCs and Standard Expansion both make use of IPacketHandler but NPCs is the only one that crashes

**Comment by Funwayguy** [comment]
Missed the email notice last time but I got this one.

Kinda weird how NPCs and Standard Expansion both make use of IPacketHandler but NPCs is the only one that crashes. I'll take a look at it tomorrow to see what it's doing differently.

**Comment by Funwayguy** [comment]
Turns out this is a load order issue. The mod itself is fine but NPCs is attempting to load before the base mod because I forgot to change the dependency info to be strict.

**Comment by kreezxil** [comment]
ok thanks. much appreciated.

**Comment by Funwayguy** [comment]
Just uploaded version 3.4.25 which has all its dependency info fixed up making the load order correct again. Should be downloadable as soon as Curse is finished approving it.
