### ISSUE TITLE
Title of the dialog not showing up.

### ISSUE THREAD

**Issue by DropBear77** [Funwayguy/NPC_Integration#18]
HI, 
I have installed 
Better questing 3.5.289
Better questing - NPC Integration 3.4.27
Better questing - RF Expansion 3.4.27
Better questing - Standard Expansion 3.4.149
Cusom NPC's 1.12.2(26aug18)

I created a Dialog for an NPC from Custom NPC's and then i created a task in the Better questing book.
I looked up the ID of the Dialog and used this ID in the Task. The Title is not showing up in the book, only a Text "Dialog: [?]" is showing up. I tried everything the same in the 1.10 version of minecraft and the problem dosent exist there and i did everything the same way as in the 1.12.2 version. This might be a bug??

**Comment by Funwayguy** [comment]
_looks at code_
Wow that was dumb. Forgot to make the new databases sync their own data properly. No big deal. Fix is being uploaded now.
