### ISSUE TITLE
Crash with Version 1.0.7

### ISSUE THREAD

**Issue by Dream-Master** [Funwayguy/NPC_Integration#2]
My Modpack crash since i update NPC Integration form 1.0.6 to 1.0.7.

My Modpack:

https://github.com/GTNewHorizons/NewHorizons

https://gist.github.com/Dream-Master/3681865ea37764654cd3b114cb89b759#file-crash

Open Eyes said this:
http://openeye.openmods.info/crashes/b3c23c86f19593fb317981835c476ed2

Full fml log:
https://gist.github.com/Dream-Master/8f84c47c81243e5e5eeb6bc69c9fd07e

**Comment by Funwayguy** [comment]
Seems you don't have CustomNPCs installed. NPC Integration doesn't give you NPCs (hence why it's called integration and not expansion), it hooks into the existing ones from here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1278956-custom-npcs

EDIT: For future bug reports, can you please include the proper log file, not the FML log. That one is mostly for debugging forge itself. The one you usually want is "latest.log"

**Comment by Dream-Master** [comment]
Will try to remove this mod because i dont need it atm. I let you know if it works and seend you in case the lastest log too.
