### ISSUE TITLE
Stoped server load after NPC Integration installed

### ISSUE THREAD

**Issue by EleXte** [Funwayguy/NPC_Integration#22]
I am using the latest version of BetterQuesting (3.0.322) with Standard Expansion (3.0.174 version) and everything works correctly on minecraft 1.7.10 version.

After installing NPC Integration (3.0.30 version) I get an error and the server stops. Text of error:
[Server thread/ERROR] [FML/]: Caught exception from bq_npc_integration
net.minecraft.server.MinecraftServer.getCommandManager()Lnet/minecraft/command/ICommandManager;

Trying to start a dedicated server without the world and I get the same error.

Because there is no crash I'm attaching a part of log with errors (and full mod list):
[latest (2).log](https://github.com/Funwayguy/NPC_Integration/files/4237941/latest.2.log)
Log on pastebin: https://pastebin.com/j6DW27Bi
I'm not posting a full log because not sure if 6k lines will be helpful.

**Comment by Funwayguy** [comment]
You installed the deobfuscated developer version, that's why.

**Comment by EleXte** [comment]
Really big thanks for the answer and please accept my apologies for this my fail.
