### ISSUE TITLE
Quest Completion

### ISSUE THREAD

**Issue by GreatOrator** [Funwayguy/NPC_Integration#3]
Mod Version: 1.0.8
Issue: Quest completion not registering

Description:  So when setting up quests in CustomNPC's completing a quest is not triggering the completion in Better Questing.  Does not seem to be reading the quests in the NPC folder.

**Comment by teagan75** [comment]
To better clarify, When making a task -bq npc integration quest - and putting the ID of the custom npc quest to attach, it remains a ?   Linking custom npc dialogues and factions work, just not quest.

**Comment by teagan75** [comment]
It has been a month. Do you have any update for this issue? Am I not understanding how to use this or is it an issue with custom npcs itself?

**Comment by Funwayguy** [comment]
Should be fixed now. Sorry I missed this bug report till now
