### ISSUE TITLE
Crash on GUI open

### ISSUE THREAD

**Issue by GreatOrator** [Funwayguy/NPC_Integration#6]
Getting an odd crash to desktop when on a server and trying to open the better questing GUI to edit:

http://pastebin.com/91YUww66

Using newest versions of Better Questing, Standard Expansion and NPC integration, does not seem to happen in SSP only SMP

**Comment by Funwayguy** [comment]
Just sent out a build that should address this issue

**Comment by GreatOrator** [comment]
long since fixed, thank you!
