### ISSUE TITLE
[Bug] Crash when trying to launch a new world

### ISSUE THREAD

**Issue by MysticAura** [Funwayguy/NPC_Integration#8]
MC: 1.10.2
Forge: 2185, 2151
Mod: NPCIntegration-2.3.19

Issue: Instant crash on launch. Ticking memory connection. Same issue with Standard Expansion

[Crash Log](http://pastebin.com/3jhuwVms)

**Comment by Lanse505** [comment]
I can back this issue:
https://gist.github.com/Lanse505/c849ee5fb11c1975fc355c68fd651adf 
:P

**Comment by Funwayguy** [comment]
You're both using a BQ1.x.x base with a 2.x.x expansion

**Comment by MysticAura** [comment]
Curse is a jerk...their version list isn't dated in order. If you hit update button on the mod, it updates to the release (which is 1.xx) instead of the beta 2.xx's
