### ISSUE TITLE
Task:NPC_Quest giving the Task:NPC_Dialog instead

### ISSUE THREAD

**Issue by Sir-Chi** [Funwayguy/NPC_Integration#9]
I'm getting a strange problem, that when I select the Quest Task it gives the me the Dialog Task instead. (Tested with the latest NPC Integration - 2.0.18, and Better Questing - 2.0.224)

![2017-02-22_09 33 08](https://cloud.githubusercontent.com/assets/17249849/23205498/fa1ea4a2-f8e1-11e6-9318-e861e8626d20.png)

If you could tell me if i'm doing something wrong, I'd appreciate it. And thanks again for making these amazing mods!

**Comment by Funwayguy** [comment]
Looks like I messed up the task IDs... again >_>
I'm a bit bogged down in Uni work right now so I don't know when I'll get to sorting this out but I'm hoping I'll have some time this weekend to get this fixed up.

**Comment by Sir-Chi** [comment]
Thanks for the reply, I'll be looking forward to the fix. Thanks again!
-SC
